# Generated by Django 4.2.4 on 2024-07-16 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_remove_licenseapplication_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='license_applications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
